// <auto-generated />
using System;
using Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Database.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20251229223635_AddSupportTicketSource")]
    partial class AddSupportTicketSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PreferredChannel")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Store")
                        .HasColumnType("int");

                    b.Property<int>("Subscription")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Common.EmailText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmailTexts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "<h1>Welcome to Birthday Reminder!</h1>\r\n<p>Thank you for joining Birthday Reminder. We're excited to help you never forget an important birthday again.</p>\r\n<p>Get started by adding your first birthday reminder in the app.</p>\r\n<p>Best regards,<br>The Birthday Reminder Team</p>",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsHtml = true,
                            Name = "Welcome",
                            Subject = "Welcome to Birthday Reminder!"
                        },
                        new
                        {
                            Id = 2,
                            Content = "<h1>Birthday Reminder</h1>\r\n<p>Don't forget! <strong>{Name}</strong>'s birthday is on <strong>{Date}</strong>.</p>\r\n<p>You have {DaysLeft} days to prepare a gift or send your wishes.</p>\r\n<p>Best regards,<br>The Birthday Reminder Team</p>",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsHtml = true,
                            Name = "Birthday Reminder",
                            Subject = "Birthday Reminder: {Name}'s birthday is coming up!"
                        },
                        new
                        {
                            Id = 3,
                            Content = "<h1>Support Request Received</h1>\r\n<p>Thank you for contacting us. We have received your support request.</p>\r\n<p><strong>Ticket ID:</strong> #{TicketId}<br>\r\n<strong>Subject:</strong> {Subject}</p>\r\n<p>Our team will review your request and get back to you as soon as possible.</p>\r\n<p>Best regards,<br>The Birthday Reminder Support Team</p>",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsHtml = true,
                            Name = "Support Ticket Created",
                            Subject = "Support Ticket #{TicketId} - We received your request"
                        },
                        new
                        {
                            Id = 4,
                            Content = "<h1>New Response to Your Support Ticket</h1>\r\n<p>There is a new response to your support ticket #{TicketId}.</p>\r\n<p><strong>Response:</strong></p>\r\n<blockquote>{Message}</blockquote>\r\n<p>If you have any further questions, please reply to this email.</p>\r\n<p>Best regards,<br>The Birthday Reminder Support Team</p>",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsHtml = true,
                            Name = "Support Ticket Response",
                            Subject = "Support Ticket #{TicketId} - New response"
                        },
                        new
                        {
                            Id = 5,
                            Content = "<h1>Support Ticket Closed</h1>\r\n<p>Your support ticket #{TicketId} has been closed.</p>\r\n<p>If you need further assistance, feel free to open a new support request in the app.</p>\r\n<p>Thank you for using Birthday Reminder!</p>\r\n<p>Best regards,<br>The Birthday Reminder Support Team</p>",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsHtml = true,
                            Name = "Support Ticket Closed",
                            Subject = "Support Ticket #{TicketId} - Closed"
                        });
                });

            modelBuilder.Entity("Common.MessengerText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreviewText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MessengerTexts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Channel = 3,
                            Content = "Hey! Just a friendly reminder: {Name}'s birthday is on {Date}. You have {DaysLeft} days left to prepare!",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Birthday Reminder WhatsApp",
                            PreviewText = "Birthday reminder for {Name}"
                        },
                        new
                        {
                            Id = 2,
                            Channel = 2,
                            Content = "Birthday Reminder: {Name}'s birthday is on {Date}. {DaysLeft} days left!",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Birthday Reminder SMS",
                            PreviewText = "Birthday: {Name}"
                        },
                        new
                        {
                            Id = 3,
                            Channel = 4,
                            Content = "Hey! Just a friendly reminder: {Name}'s birthday is on {Date}. You have {DaysLeft} days left to prepare!",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Birthday Reminder Signal",
                            PreviewText = "Birthday reminder for {Name}"
                        },
                        new
                        {
                            Id = 4,
                            Channel = 3,
                            Content = "New response to your support ticket #{TicketId}:\n\n{Message}\n\nReply in the app for further assistance.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Support Response WhatsApp",
                            PreviewText = "Support Ticket #{TicketId}"
                        },
                        new
                        {
                            Id = 5,
                            Channel = 2,
                            Content = "Ticket #{TicketId} update: {Message}",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Support Response SMS",
                            PreviewText = "Ticket #{TicketId}"
                        });
                });

            modelBuilder.Entity("Common.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SystemUserId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status");

                    b.HasIndex("SystemUserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("Common.SupportTicketEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFromCustomer")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportTicketId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupportTicketId");

                    b.HasIndex("SystemUserId");

                    b.ToTable("SupportTicketEntries");
                });

            modelBuilder.Entity("Common.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SystemUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin",
                            Email = "admin@birthday-reminder.online",
                            IsActive = true,
                            PasswordHash = "$2a$11$KZOBamnRyzRqTG9RLOp9f.mOMetFx3G6Mw6.0ya5cP/6sh1VY06kC"
                        });
                });

            modelBuilder.Entity("Common.SupportTicket", b =>
                {
                    b.HasOne("Common.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.SystemUser", "systemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("customer");

                    b.Navigation("systemUser");
                });

            modelBuilder.Entity("Common.SupportTicketEntry", b =>
                {
                    b.HasOne("Common.SupportTicket", "supportTicket")
                        .WithMany("Entries")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.SystemUser", "systemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("supportTicket");

                    b.Navigation("systemUser");
                });

            modelBuilder.Entity("Common.SupportTicket", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
