//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MobileLanguages;

public class Resources
{
	private static global::System.Resources.ResourceManager? resourceMan;
	private static global::System.Globalization.CultureInfo? resourceCulture;

	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (resourceMan is null)
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileLanguages.Resources", typeof(Resources).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}

	public static global::System.Globalization.CultureInfo? Culture
	{
		get { return resourceCulture; }
		set { resourceCulture = value; }
	}

	public static string Page_Main_Title => ResourceManager.GetString("Page_Main_Title", resourceCulture) ?? "";
	public static string Page_Main_MissedTitle => ResourceManager.GetString("Page_Main_MissedTitle", resourceCulture) ?? "";
	public static string Page_Main_UpcomingTitle => ResourceManager.GetString("Page_Main_UpcomingTitle", resourceCulture) ?? "";
	public static string Page_Main_NewBirthday => ResourceManager.GetString("Page_Main_NewBirthday", resourceCulture) ?? "";
	public static string Page_AskForContacts_Title => ResourceManager.GetString("Page_AskForContacts_Title", resourceCulture) ?? "";
	public static string Page_AskForContacts_Question => ResourceManager.GetString("Page_AskForContacts_Question", resourceCulture) ?? "";
	public static string Page_AskForContacts_ManualInput => ResourceManager.GetString("Page_AskForContacts_ManualInput", resourceCulture) ?? "";
	public static string Page_AskForContacts_FromContacts => ResourceManager.GetString("Page_AskForContacts_FromContacts", resourceCulture) ?? "";
	public static string Page_NewBirthday_Title => ResourceManager.GetString("Page_NewBirthday_Title", resourceCulture) ?? "";
	public static string Page_AllBirthdays_Title => ResourceManager.GetString("Page_AllBirthdays_Title", resourceCulture) ?? "";
	public static string Page_Settings_Title => ResourceManager.GetString("Page_Settings_Title", resourceCulture) ?? "";
	public static string Page_Privacy_Title => ResourceManager.GetString("Page_Privacy_Title", resourceCulture) ?? "";
	public static string Page_Help_Title => ResourceManager.GetString("Page_Help_Title", resourceCulture) ?? "";
	public static string More_Informations => ResourceManager.GetString("More_Informations", resourceCulture) ?? "";
	public static string Help_UseContacts_Header => ResourceManager.GetString("Help_UseContacts_Header", resourceCulture) ?? "";
	public static string Help_UseContacts_Content => ResourceManager.GetString("Help_UseContacts_Content", resourceCulture) ?? "";
	public static string Help_BirthdayCalendar_Header => ResourceManager.GetString("Help_BirthdayCalendar_Header", resourceCulture) ?? "";
	public static string Help_BirthdayCalendar_Content => ResourceManager.GetString("Help_BirthdayCalendar_Content", resourceCulture) ?? "";
	public static string Tab_ShowAll => ResourceManager.GetString("Tab_ShowAll", resourceCulture) ?? "";
	public static string Tab_Settings => ResourceManager.GetString("Tab_Settings", resourceCulture) ?? "";
	public static string Tab_Privacy => ResourceManager.GetString("Tab_Privacy", resourceCulture) ?? "";
	public static string General_Button_Save => ResourceManager.GetString("General_Button_Save", resourceCulture) ?? "";
	public static string General_Button_Cancel => ResourceManager.GetString("General_Button_Cancel", resourceCulture) ?? "";
	public static string General_Button_Delete => ResourceManager.GetString("General_Button_Delete", resourceCulture) ?? "";
	public static string General_Button_New => ResourceManager.GetString("General_Button_New", resourceCulture) ?? "";
	public static string General_Label_Name => ResourceManager.GetString("General_Label_Name", resourceCulture) ?? "";
	public static string General_Label_FirstName => ResourceManager.GetString("General_Label_FirstName", resourceCulture) ?? "";
	public static string General_Label_LastName => ResourceManager.GetString("General_Label_LastName", resourceCulture) ?? "";
	public static string General_Label_Birthday => ResourceManager.GetString("General_Label_Birthday", resourceCulture) ?? "";
	public static string General_Button_Next => ResourceManager.GetString("General_Button_Next", resourceCulture) ?? "";
	public static string General_Button_Back => ResourceManager.GetString("General_Button_Back", resourceCulture) ?? "";
	public static string General_Button_Finish => ResourceManager.GetString("General_Button_Finish", resourceCulture) ?? "";
	public static string General_Button_OK => ResourceManager.GetString("General_Button_OK", resourceCulture) ?? "";
	public static string General_Label_Day => ResourceManager.GetString("General_Label_Day", resourceCulture) ?? "";
	public static string General_Label_Month => ResourceManager.GetString("General_Label_Month", resourceCulture) ?? "";
	public static string Birthday_WithYear => ResourceManager.GetString("Birthday_WithYear", resourceCulture) ?? "";
	public static string Birthday_WithoutYear => ResourceManager.GetString("Birthday_WithoutYear", resourceCulture) ?? "";
	public static string Birthday_EnterDate => ResourceManager.GetString("Birthday_EnterDate", resourceCulture) ?? "";
	public static string Button_LetsGo => ResourceManager.GetString("Button_LetsGo", resourceCulture) ?? "";
	public static string Page_Welcome_Title => ResourceManager.GetString("Page_Welcome_Title", resourceCulture) ?? "";
	public static string Welcome_Header => ResourceManager.GetString("Welcome_Header", resourceCulture) ?? "";
	public static string Welcome_DataSources => ResourceManager.GetString("Welcome_DataSources", resourceCulture) ?? "";
	public static string Settings_Language => ResourceManager.GetString("Settings_Language", resourceCulture) ?? "";
	public static string Settings_ReminderTime => ResourceManager.GetString("Settings_ReminderTime", resourceCulture) ?? "";
	public static string Time_Hours => ResourceManager.GetString("Time_Hours", resourceCulture) ?? "";
	public static string Time_Minutes => ResourceManager.GetString("Time_Minutes", resourceCulture) ?? "";
	public static string Settings_Contacts => ResourceManager.GetString("Settings_Contacts", resourceCulture) ?? "";
	public static string Settings_ContactsRead => ResourceManager.GetString("Settings_ContactsRead", resourceCulture) ?? "";
	public static string Settings_ContactsReadWrite => ResourceManager.GetString("Settings_ContactsReadWrite", resourceCulture) ?? "";
	public static string Settings_ContactsBirthdayCalendar => ResourceManager.GetString("Settings_ContactsBirthdayCalendar", resourceCulture) ?? "";
	public static string Settings_ContactsNone => ResourceManager.GetString("Settings_ContactsNone", resourceCulture) ?? "";
	public static string Settings_WriteCalendarsMultiple => ResourceManager.GetString("Settings_WriteCalendarsMultiple", resourceCulture) ?? "";
	public static string Settings_Calendars => ResourceManager.GetString("Settings_Calendars", resourceCulture) ?? "";
	public static string Settings_ReadCalendars => ResourceManager.GetString("Settings_ReadCalendars", resourceCulture) ?? "";
	public static string Settings_WriteCalendars => ResourceManager.GetString("Settings_WriteCalendars", resourceCulture) ?? "";
	public static string Settings_SelectCalendars => ResourceManager.GetString("Settings_SelectCalendars", resourceCulture) ?? "";
	public static string Permission_Required => ResourceManager.GetString("Permission_Required", resourceCulture) ?? "";
	public static string Permission_ContactsRead_Denied => ResourceManager.GetString("Permission_ContactsRead_Denied", resourceCulture) ?? "";
	public static string Permission_ContactsWrite_Denied => ResourceManager.GetString("Permission_ContactsWrite_Denied", resourceCulture) ?? "";
	public static string Permission_CalendarRead_Denied => ResourceManager.GetString("Permission_CalendarRead_Denied", resourceCulture) ?? "";
	public static string Permission_CalendarWrite_Denied => ResourceManager.GetString("Permission_CalendarWrite_Denied", resourceCulture) ?? "";
	public static string Calendar_Default => ResourceManager.GetString("Calendar_Default", resourceCulture) ?? "";
	public static string Calendar_Personal => ResourceManager.GetString("Calendar_Personal", resourceCulture) ?? "";
	public static string Calendar_Work => ResourceManager.GetString("Calendar_Work", resourceCulture) ?? "";
	public static string Calendar_Family => ResourceManager.GetString("Calendar_Family", resourceCulture) ?? "";
	public static string Settings_Saved_Title => ResourceManager.GetString("Settings_Saved_Title", resourceCulture) ?? "";
	public static string Settings_Saved_Message => ResourceManager.GetString("Settings_Saved_Message", resourceCulture) ?? "";
	public static string Welcome_Header_Title => ResourceManager.GetString("Welcome_Header_Title", resourceCulture) ?? "";
	public static string Welcome_1_Text_1 => ResourceManager.GetString("Welcome_1_Text_1", resourceCulture) ?? "";
	public static string Welcome_1_Text_2 => ResourceManager.GetString("Welcome_1_Text_2", resourceCulture) ?? "";
	public static string Settings_Theme => ResourceManager.GetString("Settings_Theme", resourceCulture) ?? "";
	public static string Settings_Theme_Light => ResourceManager.GetString("Settings_Theme_Light", resourceCulture) ?? "";
	public static string Settings_Theme_Dark => ResourceManager.GetString("Settings_Theme_Dark", resourceCulture) ?? "";
	public static string Settings_Theme_System => ResourceManager.GetString("Settings_Theme_System", resourceCulture) ?? "";
	public static string Date_Day => ResourceManager.GetString("Date_Day", resourceCulture) ?? "";
	public static string Date_Month => ResourceManager.GetString("Date_Month", resourceCulture) ?? "";
	public static string Date_Year => ResourceManager.GetString("Date_Year", resourceCulture) ?? "";
	public static string Month_January => ResourceManager.GetString("Month_January", resourceCulture) ?? "";
	public static string Month_February => ResourceManager.GetString("Month_February", resourceCulture) ?? "";
	public static string Month_March => ResourceManager.GetString("Month_March", resourceCulture) ?? "";
	public static string Month_April => ResourceManager.GetString("Month_April", resourceCulture) ?? "";
	public static string Month_May => ResourceManager.GetString("Month_May", resourceCulture) ?? "";
	public static string Month_June => ResourceManager.GetString("Month_June", resourceCulture) ?? "";
	public static string Month_July => ResourceManager.GetString("Month_July", resourceCulture) ?? "";
	public static string Month_August => ResourceManager.GetString("Month_August", resourceCulture) ?? "";
	public static string Month_September => ResourceManager.GetString("Month_September", resourceCulture) ?? "";
	public static string Month_October => ResourceManager.GetString("Month_October", resourceCulture) ?? "";
	public static string Month_November => ResourceManager.GetString("Month_November", resourceCulture) ?? "";
	public static string Month_December => ResourceManager.GetString("Month_December", resourceCulture) ?? "";
	public static string Month_Short_Jan => ResourceManager.GetString("Month_Short_Jan", resourceCulture) ?? "";
	public static string Month_Short_Feb => ResourceManager.GetString("Month_Short_Feb", resourceCulture) ?? "";
	public static string Month_Short_Mar => ResourceManager.GetString("Month_Short_Mar", resourceCulture) ?? "";
	public static string Month_Short_Apr => ResourceManager.GetString("Month_Short_Apr", resourceCulture) ?? "";
	public static string Month_Short_May => ResourceManager.GetString("Month_Short_May", resourceCulture) ?? "";
	public static string Month_Short_Jun => ResourceManager.GetString("Month_Short_Jun", resourceCulture) ?? "";
	public static string Month_Short_Jul => ResourceManager.GetString("Month_Short_Jul", resourceCulture) ?? "";
	public static string Month_Short_Aug => ResourceManager.GetString("Month_Short_Aug", resourceCulture) ?? "";
	public static string Month_Short_Sep => ResourceManager.GetString("Month_Short_Sep", resourceCulture) ?? "";
	public static string Month_Short_Oct => ResourceManager.GetString("Month_Short_Oct", resourceCulture) ?? "";
	public static string Month_Short_Nov => ResourceManager.GetString("Month_Short_Nov", resourceCulture) ?? "";
	public static string Month_Short_Dec => ResourceManager.GetString("Month_Short_Dec", resourceCulture) ?? "";
	public static string Settings_ShowUpcomingBirthdays => ResourceManager.GetString("Settings_ShowUpcomingBirthdays", resourceCulture) ?? "";
	public static string Settings_ShowPastBirthdays => ResourceManager.GetString("Settings_ShowPastBirthdays", resourceCulture) ?? "";
	public static string Settings_Display => ResourceManager.GetString("Settings_Display", resourceCulture) ?? "";
	public static string Reminder_Label => ResourceManager.GetString("Reminder_Label", resourceCulture) ?? "";
	public static string ReminderMethod_Label => ResourceManager.GetString("ReminderMethod_Label", resourceCulture) ?? "";
	public static string ReminderMethod_NotSet => ResourceManager.GetString("ReminderMethod_NotSet", resourceCulture) ?? "";
	public static string ReminderMethod_Email => ResourceManager.GetString("ReminderMethod_Email", resourceCulture) ?? "";
	public static string ReminderMethod_Sms => ResourceManager.GetString("ReminderMethod_Sms", resourceCulture) ?? "";
	public static string ReminderMethod_LockScreen => ResourceManager.GetString("ReminderMethod_LockScreen", resourceCulture) ?? "";
	public static string ReminderMethod_WhatsApp => ResourceManager.GetString("ReminderMethod_WhatsApp", resourceCulture) ?? "";
	public static string RemindUntilApproved_Label => ResourceManager.GetString("RemindUntilApproved_Label", resourceCulture) ?? "";
	public static string Button_ConfigureReminders => ResourceManager.GetString("Button_ConfigureReminders", resourceCulture) ?? "";
	public static string Placeholder_FirstName => ResourceManager.GetString("Placeholder_FirstName", resourceCulture) ?? "";
	public static string Placeholder_LastName => ResourceManager.GetString("Placeholder_LastName", resourceCulture) ?? "";
	public static string Settings_NoReminders => ResourceManager.GetString("Settings_NoReminders", resourceCulture) ?? "";
	public static string Age_WillTurn => ResourceManager.GetString("Age_WillTurn", resourceCulture) ?? "";
	public static string Filter_AllMonths => ResourceManager.GetString("Filter_AllMonths", resourceCulture) ?? "";
	public static string Tab_Overview => ResourceManager.GetString("Tab_Overview", resourceCulture) ?? "";
}
