//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileLanguages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileLanguages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not set ähnelt.
        /// </summary>
        public static string Account_NoEmail {
            get {
                return ResourceManager.GetString("Account_NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subscription ähnelt.
        /// </summary>
        public static string Account_Subscription {
            get {
                return ResourceManager.GetString("Account_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plan ähnelt.
        /// </summary>
        public static string Account_SubscriptionTier {
            get {
                return ResourceManager.GetString("Account_SubscriptionTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlimited ähnelt.
        /// </summary>
        public static string Account_Unlimited {
            get {
                return ResourceManager.GetString("Account_Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Valid until ähnelt.
        /// </summary>
        public static string Account_ValidUntil {
            get {
                return ResourceManager.GetString("Account_ValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} years ähnelt.
        /// </summary>
        public static string Age_WillTurn {
            get {
                return ResourceManager.GetString("Age_WillTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} years old ähnelt.
        /// </summary>
        public static string Age_Years {
            get {
                return ResourceManager.GetString("Age_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter date (DD.MM.YYYY) ähnelt.
        /// </summary>
        public static string Birthday_EnterDate {
            get {
                return ResourceManager.GetString("Birthday_EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter year (0000 = no year) ähnelt.
        /// </summary>
        public static string Birthday_EnterYear {
            get {
                return ResourceManager.GetString("Birthday_EnterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In {0} days ähnelt.
        /// </summary>
        public static string Birthday_InDays {
            get {
                return ResourceManager.GetString("Birthday_InDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Today! ähnelt.
        /// </summary>
        public static string Birthday_Today {
            get {
                return ResourceManager.GetString("Birthday_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tomorrow ähnelt.
        /// </summary>
        public static string Birthday_Tomorrow {
            get {
                return ResourceManager.GetString("Birthday_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Without birth year ähnelt.
        /// </summary>
        public static string Birthday_WithoutYear {
            get {
                return ResourceManager.GetString("Birthday_WithoutYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die With birth year ähnelt.
        /// </summary>
        public static string Birthday_WithYear {
            get {
                return ResourceManager.GetString("Birthday_WithYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The birthday of ähnelt.
        /// </summary>
        public static string Detail_BirthdayOf {
            get {
                return ResourceManager.GetString("Detail_BirthdayOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is on ähnelt.
        /// </summary>
        public static string Detail_IsOn {
            get {
                return ResourceManager.GetString("Detail_IsOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die He / she will turn {0} on that day ähnelt.
        /// </summary>
        public static string Detail_AgeOnThatDay {
            get {
                return ResourceManager.GetString("Detail_AgeOnThatDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die That's Today! ähnelt.
        /// </summary>
        public static string Detail_Birthday_TodayIs {
            get {
                return ResourceManager.GetString("Detail_Birthday_TodayIs", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die That's Tomorrow ähnelt.
        /// </summary>
        public static string Detail_Birthday_TomorrowIs {
            get {
                return ResourceManager.GetString("Detail_Birthday_TomorrowIs", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die That's in {0} days ähnelt.
        /// </summary>
        public static string Detail_Birthday_InDaysIs {
            get {
                return ResourceManager.GetString("Detail_Birthday_InDaysIs", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have no reminders set ähnelt.
        /// </summary>
        public static string Detail_NoReminders {
            get {
                return ResourceManager.GetString("Detail_NoReminders", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You will be reminded as follows: ähnelt.
        /// </summary>
        public static string Detail_RemindersSet {
            get {
                return ResourceManager.GetString("Detail_RemindersSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure Reminders ähnelt.
        /// </summary>
        public static string Button_ConfigureReminders {
            get {
                return ResourceManager.GetString("Button_ConfigureReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Let&apos;s go ähnelt.
        /// </summary>
        public static string Button_LetsGo {
            get {
                return ResourceManager.GetString("Button_LetsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default Calendar ähnelt.
        /// </summary>
        public static string Calendar_Default {
            get {
                return ResourceManager.GetString("Calendar_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Family ähnelt.
        /// </summary>
        public static string Calendar_Family {
            get {
                return ResourceManager.GetString("Calendar_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personal ähnelt.
        /// </summary>
        public static string Calendar_Personal {
            get {
                return ResourceManager.GetString("Calendar_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work ähnelt.
        /// </summary>
        public static string Calendar_Work {
            get {
                return ResourceManager.GetString("Calendar_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birthday with/without year ähnelt.
        /// </summary>
        public static string CardHeader_Birthday {
            get {
                return ResourceManager.GetString("CardHeader_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First and last name ähnelt.
        /// </summary>
        public static string CardHeader_Name {
            get {
                return ResourceManager.GetString("CardHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Birthday ähnelt.
        /// </summary>
        public static string CardHeader_NextBirthday {
            get {
                return ResourceManager.GetString("CardHeader_NextBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        public static string Date_Day {
            get {
                return ResourceManager.GetString("Date_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        public static string Date_Month {
            get {
                return ResourceManager.GetString("Date_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        public static string Date_Year {
            get {
                return ResourceManager.GetString("Date_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No birthdays ähnelt.
        /// </summary>
        public static string EmptyView_NoBirthdays {
            get {
                return ResourceManager.GetString("EmptyView_NoBirthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No missed birthdays ähnelt.
        /// </summary>
        public static string EmptyView_NoMissed {
            get {
                return ResourceManager.GetString("EmptyView_NoMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No upcoming birthdays ähnelt.
        /// </summary>
        public static string EmptyView_NoUpcoming {
            get {
                return ResourceManager.GetString("EmptyView_NoUpcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter at least a first or last name. ähnelt.
        /// </summary>
        public static string Error_NameRequired {
            get {
                return ResourceManager.GetString("Error_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- all -- ähnelt.
        /// </summary>
        public static string Filter_AllMonths {
            get {
                return ResourceManager.GetString("Filter_AllMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found birthdays ähnelt.
        /// </summary>
        public static string FoundBirthdays_Header {
            get {
                return ResourceManager.GetString("FoundBirthdays_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string General_Button_Back {
            get {
                return ResourceManager.GetString("General_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string General_Button_Cancel {
            get {
                return ResourceManager.GetString("General_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string General_Button_Delete {
            get {
                return ResourceManager.GetString("General_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string General_Button_Edit {
            get {
                return ResourceManager.GetString("General_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        public static string General_Button_Finish {
            get {
                return ResourceManager.GetString("General_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string General_Button_New {
            get {
                return ResourceManager.GetString("General_Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string General_Button_Next {
            get {
                return ResourceManager.GetString("General_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string General_Button_OK {
            get {
                return ResourceManager.GetString("General_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string General_Button_Save {
            get {
                return ResourceManager.GetString("General_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birthday ähnelt.
        /// </summary>
        public static string General_Label_Birthday {
            get {
                return ResourceManager.GetString("General_Label_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        public static string General_Label_Day {
            get {
                return ResourceManager.GetString("General_Label_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name ähnelt.
        /// </summary>
        public static string General_Label_FirstName {
            get {
                return ResourceManager.GetString("General_Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Name ähnelt.
        /// </summary>
        public static string General_Label_LastName {
            get {
                return ResourceManager.GetString("General_Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        public static string General_Label_Month {
            get {
                return ResourceManager.GetString("General_Label_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string General_Label_Name {
            get {
                return ResourceManager.GetString("General_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        public static string General_Label_Year {
            get {
                return ResourceManager.GetString("General_Label_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The &quot;Birthday Calendar&quot; option reads birthdays from your device&apos;s birthday calendar.
        ///
        ///Some phones automatically create a birthday calendar from your contacts. This option allows Birthday Reminder to import birthdays from that calendar. ähnelt.
        /// </summary>
        public static string Help_BirthdayCalendar_Content_1 {
            get {
                return ResourceManager.GetString("Help_BirthdayCalendar_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is useful if:
        ///• Your contacts don&apos;t have birthday fields
        ///• You already maintain a separate birthday calendar
        ///• You want to import birthdays without giving full contact access ähnelt.
        /// </summary>
        public static string Help_BirthdayCalendar_Content_2 {
            get {
                return ResourceManager.GetString("Help_BirthdayCalendar_Content_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birthday Calendar ähnelt.
        /// </summary>
        public static string Help_BirthdayCalendar_Header {
            get {
                return ResourceManager.GetString("Help_BirthdayCalendar_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can save a birthday with or without a year.
        ///
        ///If you don&apos;t know the birth year, simply choose &quot;Without year&quot; when selecting the date. The year will be displayed as &quot;0000&quot;. ähnelt.
        /// </summary>
        public static string Help_BirthdayWithoutYear_Content_1 {
            get {
                return ResourceManager.GetString("Help_BirthdayWithoutYear_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When a birthday has no year:
        ///• No age will be calculated or displayed
        ///• The reminder will still work normally
        ///• You can add the year later by editing the birthday ähnelt.
        /// </summary>
        public static string Help_BirthdayWithoutYear_Content_2 {
            get {
                return ResourceManager.GetString("Help_BirthdayWithoutYear_Content_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birthday without year ähnelt.
        /// </summary>
        public static string Help_BirthdayWithoutYear_Header {
            get {
                return ResourceManager.GetString("Help_BirthdayWithoutYear_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When you enable &quot;Contacts as source&quot;, Birthday Reminder will read birthdays from your phone&apos;s contact list.
        ///
        ///This allows you to:
        ///• Automatically import birthdays from your contacts
        ///• Keep your birthday list synchronized with your contacts
        ///• Avoid manually entering birthdays that are already stored in your contacts ähnelt.
        /// </summary>
        public static string Help_UseContacts_Content_1 {
            get {
                return ResourceManager.GetString("Help_UseContacts_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The app will only read birthday information - no other contact data is accessed or stored. ähnelt.
        /// </summary>
        public static string Help_UseContacts_Content_2 {
            get {
                return ResourceManager.GetString("Help_UseContacts_Content_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contacts as source ähnelt.
        /// </summary>
        public static string Help_UseContacts_Header {
            get {
                return ResourceManager.GetString("Help_UseContacts_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die April ähnelt.
        /// </summary>
        public static string Month_April {
            get {
                return ResourceManager.GetString("Month_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die August ähnelt.
        /// </summary>
        public static string Month_August {
            get {
                return ResourceManager.GetString("Month_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die December ähnelt.
        /// </summary>
        public static string Month_December {
            get {
                return ResourceManager.GetString("Month_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die February ähnelt.
        /// </summary>
        public static string Month_February {
            get {
                return ResourceManager.GetString("Month_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die January ähnelt.
        /// </summary>
        public static string Month_January {
            get {
                return ResourceManager.GetString("Month_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die July ähnelt.
        /// </summary>
        public static string Month_July {
            get {
                return ResourceManager.GetString("Month_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die June ähnelt.
        /// </summary>
        public static string Month_June {
            get {
                return ResourceManager.GetString("Month_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die March ähnelt.
        /// </summary>
        public static string Month_March {
            get {
                return ResourceManager.GetString("Month_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die May ähnelt.
        /// </summary>
        public static string Month_May {
            get {
                return ResourceManager.GetString("Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die November ähnelt.
        /// </summary>
        public static string Month_November {
            get {
                return ResourceManager.GetString("Month_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die October ähnelt.
        /// </summary>
        public static string Month_October {
            get {
                return ResourceManager.GetString("Month_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die September ähnelt.
        /// </summary>
        public static string Month_September {
            get {
                return ResourceManager.GetString("Month_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apr ähnelt.
        /// </summary>
        public static string Month_Short_Apr {
            get {
                return ResourceManager.GetString("Month_Short_Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aug ähnelt.
        /// </summary>
        public static string Month_Short_Aug {
            get {
                return ResourceManager.GetString("Month_Short_Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dec ähnelt.
        /// </summary>
        public static string Month_Short_Dec {
            get {
                return ResourceManager.GetString("Month_Short_Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feb ähnelt.
        /// </summary>
        public static string Month_Short_Feb {
            get {
                return ResourceManager.GetString("Month_Short_Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jan ähnelt.
        /// </summary>
        public static string Month_Short_Jan {
            get {
                return ResourceManager.GetString("Month_Short_Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jul ähnelt.
        /// </summary>
        public static string Month_Short_Jul {
            get {
                return ResourceManager.GetString("Month_Short_Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jun ähnelt.
        /// </summary>
        public static string Month_Short_Jun {
            get {
                return ResourceManager.GetString("Month_Short_Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mar ähnelt.
        /// </summary>
        public static string Month_Short_Mar {
            get {
                return ResourceManager.GetString("Month_Short_Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die May ähnelt.
        /// </summary>
        public static string Month_Short_May {
            get {
                return ResourceManager.GetString("Month_Short_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nov ähnelt.
        /// </summary>
        public static string Month_Short_Nov {
            get {
                return ResourceManager.GetString("Month_Short_Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oct ähnelt.
        /// </summary>
        public static string Month_Short_Oct {
            get {
                return ResourceManager.GetString("Month_Short_Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sep ähnelt.
        /// </summary>
        public static string Month_Short_Sep {
            get {
                return ResourceManager.GetString("Month_Short_Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More information ähnelt.
        /// </summary>
        public static string More_Informations {
            get {
                return ResourceManager.GetString("More_Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account ähnelt.
        /// </summary>
        public static string Page_Account_Title {
            get {
                return ResourceManager.GetString("Page_Account_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Birthdays ähnelt.
        /// </summary>
        public static string Page_AllBirthdays_Title {
            get {
                return ResourceManager.GetString("Page_AllBirthdays_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From Contacts ähnelt.
        /// </summary>
        public static string Page_AskForContacts_FromContacts {
            get {
                return ResourceManager.GetString("Page_AskForContacts_FromContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual Input ähnelt.
        /// </summary>
        public static string Page_AskForContacts_ManualInput {
            get {
                return ResourceManager.GetString("Page_AskForContacts_ManualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How do you want to manage birthdays? ähnelt.
        /// </summary>
        public static string Page_AskForContacts_Question {
            get {
                return ResourceManager.GetString("Page_AskForContacts_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup ähnelt.
        /// </summary>
        public static string Page_AskForContacts_Title {
            get {
                return ResourceManager.GetString("Page_AskForContacts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birthday Details ähnelt.
        /// </summary>
        public static string Page_BirthdayDetail_Title {
            get {
                return ResourceManager.GetString("Page_BirthdayDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Birthday ähnelt.
        /// </summary>
        public static string Page_DeleteBirthday_Title {
            get {
                return ResourceManager.GetString("Page_DeleteBirthday_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Birthday ähnelt.
        /// </summary>
        public static string Page_EditBirthday_Title {
            get {
                return ResourceManager.GetString("Page_EditBirthday_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string Page_Help_Title {
            get {
                return ResourceManager.GetString("Page_Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Past Birthdays ({0}) ähnelt.
        /// </summary>
        public static string Page_Main_MissedTitle {
            get {
                return ResourceManager.GetString("Page_Main_MissedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Birthday ähnelt.
        /// </summary>
        public static string Page_Main_NewBirthday {
            get {
                return ResourceManager.GetString("Page_Main_NewBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birthday Reminder ähnelt.
        /// </summary>
        public static string Page_Main_Title {
            get {
                return ResourceManager.GetString("Page_Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upcoming Birthdays ({0}) ähnelt.
        /// </summary>
        public static string Page_Main_UpcomingTitle {
            get {
                return ResourceManager.GetString("Page_Main_UpcomingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Birthday ähnelt.
        /// </summary>
        public static string Page_NewBirthday_Title {
            get {
                return ResourceManager.GetString("Page_NewBirthday_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        public static string Page_Privacy_Title {
            get {
                return ResourceManager.GetString("Page_Privacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder Settings ähnelt.
        /// </summary>
        public static string Page_ReminderSettings_Title {
            get {
                return ResourceManager.GetString("Page_ReminderSettings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure your reminders. Tap a card to edit. ähnelt.
        /// </summary>
        public static string ReminderSettings_Description {
            get {
                return ResourceManager.GetString("ReminderSettings_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} days before ähnelt.
        /// </summary>
        public static string ReminderSettings_DaysBefore {
            get {
                return ResourceManager.GetString("ReminderSettings_DaysBefore", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not configured yet ähnelt.
        /// </summary>
        public static string ReminderSettings_NotConfigured {
            get {
                return ResourceManager.GetString("ReminderSettings_NotConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No methods enabled ähnelt.
        /// </summary>
        public static string ReminderSettings_NoMethods {
            get {
                return ResourceManager.GetString("ReminderSettings_NoMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Page_Settings_Title {
            get {
                return ResourceManager.GetString("Page_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome ähnelt.
        /// </summary>
        public static string Page_Welcome_Title {
            get {
                return ResourceManager.GetString("Page_Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendar read permission is required for this feature. Please enable it in settings. ähnelt.
        /// </summary>
        public static string Permission_CalendarRead_Denied {
            get {
                return ResourceManager.GetString("Permission_CalendarRead_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendar write permission is required for this feature. Please enable it in settings. ähnelt.
        /// </summary>
        public static string Permission_CalendarWrite_Denied {
            get {
                return ResourceManager.GetString("Permission_CalendarWrite_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact read permission is required for this feature. Please enable it in settings. ähnelt.
        /// </summary>
        public static string Permission_ContactsRead_Denied {
            get {
                return ResourceManager.GetString("Permission_ContactsRead_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact write permission is required for this feature. Please enable it in settings. ähnelt.
        /// </summary>
        public static string Permission_ContactsWrite_Denied {
            get {
                return ResourceManager.GetString("Permission_ContactsWrite_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission Required ähnelt.
        /// </summary>
        public static string Permission_Required {
            get {
                return ResourceManager.GetString("Permission_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter first name ähnelt.
        /// </summary>
        public static string Placeholder_FirstName {
            get {
                return ResourceManager.GetString("Placeholder_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter last name ähnelt.
        /// </summary>
        public static string Placeholder_LastName {
            get {
                return ResourceManager.GetString("Placeholder_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy Policy ähnelt.
        /// </summary>
        public static string Privacy_Header {
            get {
                return ResourceManager.GetString("Privacy_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your birthday data is stored locally on your device only. ähnelt.
        /// </summary>
        public static string Privacy_Text_1 {
            get {
                return ResourceManager.GetString("Privacy_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you choose to sync with contacts, we only read birthday information and names. We never upload your data to any server. ähnelt.
        /// </summary>
        public static string Privacy_Text_2 {
            get {
                return ResourceManager.GetString("Privacy_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All data remains on your device and under your control. ähnelt.
        /// </summary>
        public static string Privacy_Text_3 {
            get {
                return ResourceManager.GetString("Privacy_Text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Reminders ähnelt.
        /// </summary>
        public static string Reminder_Label {
            get {
                return ResourceManager.GetString("Reminder_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No reminders ähnelt.
        /// </summary>
        public static string ReminderCount_None {
            get {
                return ResourceManager.GetString("ReminderCount_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 reminder ähnelt.
        /// </summary>
        public static string ReminderCount_One {
            get {
                return ResourceManager.GetString("ReminderCount_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 reminders ähnelt.
        /// </summary>
        public static string ReminderCount_Three {
            get {
                return ResourceManager.GetString("ReminderCount_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2 reminders ähnelt.
        /// </summary>
        public static string ReminderCount_Two {
            get {
                return ResourceManager.GetString("ReminderCount_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm ähnelt.
        /// </summary>
        public static string ReminderMethod_Alarm {
            get {
                return ResourceManager.GetString("ReminderMethod_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string ReminderMethod_Email {
            get {
                return ResourceManager.GetString("ReminderMethod_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder Method ähnelt.
        /// </summary>
        public static string ReminderMethod_Label {
            get {
                return ResourceManager.GetString("ReminderMethod_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lock Screen ähnelt.
        /// </summary>
        public static string ReminderMethod_LockScreen {
            get {
                return ResourceManager.GetString("ReminderMethod_LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notification ähnelt.
        /// </summary>
        public static string ReminderMethod_Notification {
            get {
                return ResourceManager.GetString("ReminderMethod_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not set ähnelt.
        /// </summary>
        public static string ReminderMethod_NotSet {
            get {
                return ResourceManager.GetString("ReminderMethod_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal ähnelt.
        /// </summary>
        public static string ReminderMethod_Signal {
            get {
                return ResourceManager.GetString("ReminderMethod_Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMS ähnelt.
        /// </summary>
        public static string ReminderMethod_Sms {
            get {
                return ResourceManager.GetString("ReminderMethod_Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WhatsApp ähnelt.
        /// </summary>
        public static string ReminderMethod_WhatsApp {
            get {
                return ResourceManager.GetString("ReminderMethod_WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Name} is turning {Age} years old. ähnelt.
        /// </summary>
        public static string ReminderTemplate_AgeText {
            get {
                return ResourceManager.GetString("ReminderTemplate_AgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hello,
        ///
        ///I would like to remind you that {Name} has a birthday in {Days} days ({Date}). {AgeText}
        ///
        ///{Goodbye}
        ///
        ///{TeamSignature} ähnelt.
        /// </summary>
        public static string ReminderTemplate_Email_InDays {
            get {
                return ResourceManager.GetString("ReminderTemplate_Email_InDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hello,
        ///
        ///I would like to remind you that {Name} has a birthday today ({Date}). {AgeText}
        ///
        ///{Goodbye}
        ///
        ///{TeamSignature} ähnelt.
        /// </summary>
        public static string ReminderTemplate_Email_Today {
            get {
                return ResourceManager.GetString("ReminderTemplate_Email_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hello,
        ///
        ///I would like to remind you that {Name} has a birthday tomorrow ({Date}). {AgeText}
        ///
        ///{Goodbye}
        ///
        ///{TeamSignature} ähnelt.
        /// </summary>
        public static string ReminderTemplate_Email_Tomorrow {
            get {
                return ResourceManager.GetString("ReminderTemplate_Email_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Best regards ähnelt.
        /// </summary>
        public static string ReminderTemplate_Goodbye {
            get {
                return ResourceManager.GetString("ReminderTemplate_Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder: {Name} has a birthday in {Days} days ({Date})! {AgeText} ähnelt.
        /// </summary>
        public static string ReminderTemplate_Signal_InDays {
            get {
                return ResourceManager.GetString("ReminderTemplate_Signal_InDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder: {Name} has a birthday today ({Date})! {AgeText} ähnelt.
        /// </summary>
        public static string ReminderTemplate_Signal_Today {
            get {
                return ResourceManager.GetString("ReminderTemplate_Signal_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder: {Name} has a birthday tomorrow ({Date})! {AgeText} ähnelt.
        /// </summary>
        public static string ReminderTemplate_Signal_Tomorrow {
            get {
                return ResourceManager.GetString("ReminderTemplate_Signal_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder: {Name} has a birthday in {Days} days ({Date})! {AgeText} ähnelt.
        /// </summary>
        public static string ReminderTemplate_Sms_InDays {
            get {
                return ResourceManager.GetString("ReminderTemplate_Sms_InDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder: {Name} has a birthday today ({Date})! {AgeText} ähnelt.
        /// </summary>
        public static string ReminderTemplate_Sms_Today {
            get {
                return ResourceManager.GetString("ReminderTemplate_Sms_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder: {Name} has a birthday tomorrow ({Date})! {AgeText} ähnelt.
        /// </summary>
        public static string ReminderTemplate_Sms_Tomorrow {
            get {
                return ResourceManager.GetString("ReminderTemplate_Sms_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your team from {Domain} ähnelt.
        /// </summary>
        public static string ReminderTemplate_TeamSignature {
            get {
                return ResourceManager.GetString("ReminderTemplate_TeamSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hey! {Name} has a birthday in {Days} days ({Date})! 🎂 {AgeText} ähnelt.
        /// </summary>
        public static string ReminderTemplate_WhatsApp_InDays {
            get {
                return ResourceManager.GetString("ReminderTemplate_WhatsApp_InDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hey! {Name} has a birthday today ({Date})! 🎂 {AgeText} ähnelt.
        /// </summary>
        public static string ReminderTemplate_WhatsApp_Today {
            get {
                return ResourceManager.GetString("ReminderTemplate_WhatsApp_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hey! {Name} has a birthday tomorrow ({Date})! 🎂 {AgeText} ähnelt.
        /// </summary>
        public static string ReminderTemplate_WhatsApp_Tomorrow {
            get {
                return ResourceManager.GetString("ReminderTemplate_WhatsApp_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remind until approved ähnelt.
        /// </summary>
        public static string RemindUntilApproved_Label {
            get {
                return ResourceManager.GetString("RemindUntilApproved_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new entry ähnelt.
        /// </summary>
        public static string SearchPerson_CreateNew {
            get {
                return ResourceManager.GetString("SearchPerson_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search for an existing entry or create a new one. ähnelt.
        /// </summary>
        public static string SearchPerson_Description {
            get {
                return ResourceManager.GetString("SearchPerson_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No entries found ähnelt.
        /// </summary>
        public static string SearchPerson_NoResults {
            get {
                return ResourceManager.GetString("SearchPerson_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string SearchPerson_SearchHeader {
            get {
                return ResourceManager.GetString("SearchPerson_SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter name... ähnelt.
        /// </summary>
        public static string SearchPerson_SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPerson_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendars ähnelt.
        /// </summary>
        public static string Settings_Calendars {
            get {
                return ResourceManager.GetString("Settings_Calendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contacts ähnelt.
        /// </summary>
        public static string Settings_Contacts {
            get {
                return ResourceManager.GetString("Settings_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read once from birthday calendar ähnelt.
        /// </summary>
        public static string Settings_ContactsBirthdayCalendar {
            get {
                return ResourceManager.GetString("Settings_ContactsBirthdayCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No access allowed ähnelt.
        /// </summary>
        public static string Settings_ContactsNone {
            get {
                return ResourceManager.GetString("Settings_ContactsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contacts as source ähnelt.
        /// </summary>
        public static string Settings_ContactsRead {
            get {
                return ResourceManager.GetString("Settings_ContactsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contacts as source and write back ähnelt.
        /// </summary>
        public static string Settings_ContactsReadWrite {
            get {
                return ResourceManager.GetString("Settings_ContactsReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create contact entry ähnelt.
        /// </summary>
        public static string Settings_CreateContact {
            get {
                return ResourceManager.GetString("Settings_CreateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days before ähnelt.
        /// </summary>
        public static string Settings_DaysBefore {
            get {
                return ResourceManager.GetString("Settings_DaysBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Also delete from contacts ähnelt.
        /// </summary>
        public static string Settings_DeleteContact {
            get {
                return ResourceManager.GetString("Settings_DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display ähnelt.
        /// </summary>
        public static string Settings_Display {
            get {
                return ResourceManager.GetString("Settings_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Language ähnelt.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t use reminders ähnelt.
        /// </summary>
        public static string Settings_NoReminders {
            get {
                return ResourceManager.GetString("Settings_NoReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read from calendars ähnelt.
        /// </summary>
        public static string Settings_ReadCalendars {
            get {
                return ResourceManager.GetString("Settings_ReadCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import birthday events from your calendars ähnelt.
        /// </summary>
        public static string Settings_ReadCalendars_Desc {
            get {
                return ResourceManager.GetString("Settings_ReadCalendars_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder 1 ähnelt.
        /// </summary>
        public static string Settings_Reminder_1 {
            get {
                return ResourceManager.GetString("Settings_Reminder_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder 2 ähnelt.
        /// </summary>
        public static string Settings_Reminder_2 {
            get {
                return ResourceManager.GetString("Settings_Reminder_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder 3 ähnelt.
        /// </summary>
        public static string Settings_Reminder_3 {
            get {
                return ResourceManager.GetString("Settings_Reminder_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of Reminders ähnelt.
        /// </summary>
        public static string Settings_ReminderCount {
            get {
                return ResourceManager.GetString("Settings_ReminderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder Methods ähnelt.
        /// </summary>
        public static string Settings_ReminderMethods {
            get {
                return ResourceManager.GetString("Settings_ReminderMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set reminders manually ähnelt.
        /// </summary>
        public static string Settings_RemindersManual {
            get {
                return ResourceManager.GetString("Settings_RemindersManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder Time ähnelt.
        /// </summary>
        public static string Settings_ReminderTime {
            get {
                return ResourceManager.GetString("Settings_ReminderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings saved successfully ähnelt.
        /// </summary>
        public static string Settings_Saved_Message {
            get {
                return ResourceManager.GetString("Settings_Saved_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings_Saved_Title {
            get {
                return ResourceManager.GetString("Settings_Saved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select calendars: ähnelt.
        /// </summary>
        public static string Settings_SelectCalendars {
            get {
                return ResourceManager.GetString("Settings_SelectCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Past Birthdays ähnelt.
        /// </summary>
        public static string Settings_ShowPastBirthdays {
            get {
                return ResourceManager.GetString("Settings_ShowPastBirthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upcoming Birthdays ähnelt.
        /// </summary>
        public static string Settings_ShowUpcomingBirthdays {
            get {
                return ResourceManager.GetString("Settings_ShowUpcomingBirthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Theme ähnelt.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Default ähnelt.
        /// </summary>
        public static string Settings_Theme_System {
            get {
                return ResourceManager.GetString("Settings_Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update contact entry ähnelt.
        /// </summary>
        public static string Settings_UpdateContact {
            get {
                return ResourceManager.GetString("Settings_UpdateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write to calendars ähnelt.
        /// </summary>
        public static string Settings_WriteCalendars {
            get {
                return ResourceManager.GetString("Settings_WriteCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create birthday events in your calendars ähnelt.
        /// </summary>
        public static string Settings_WriteCalendars_Desc {
            get {
                return ResourceManager.GetString("Settings_WriteCalendars_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write back to selected calendars ähnelt.
        /// </summary>
        public static string Settings_WriteCalendarsMultiple {
            get {
                return ResourceManager.GetString("Settings_WriteCalendarsMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save to contact ähnelt.
        /// </summary>
        public static string Settings_WriteToContact {
            get {
                return ResourceManager.GetString("Settings_WriteToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ask for options on next page ähnelt.
        /// </summary>
        public static string Start2_AskNextPage {
            get {
                return ResourceManager.GetString("Start2_AskNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No use of my contacts ähnelt.
        /// </summary>
        public static string Start2_NoContacts {
            get {
                return ResourceManager.GetString("Start2_NoContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Each of your contacts has a birthday field in addition to first and last name. ähnelt.
        /// </summary>
        public static string Start2_Text_1 {
            get {
                return ResourceManager.GetString("Start2_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to use that or stay completely separate and enter everything new here? ähnelt.
        /// </summary>
        public static string Start2_Text_2 {
            get {
                return ResourceManager.GetString("Start2_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use contacts? ähnelt.
        /// </summary>
        public static string Start2_UseContacts {
            get {
                return ResourceManager.GetString("Start2_UseContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All contacts ähnelt.
        /// </summary>
        public static string Start3_AllContacts {
            get {
                return ResourceManager.GetString("Start3_AllContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In what way? ähnelt.
        /// </summary>
        public static string Start3_HowToSync {
            get {
                return ResourceManager.GetString("Start3_HowToSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only contacts with birthday ähnelt.
        /// </summary>
        public static string Start3_OnlyWithBirthday {
            get {
                return ResourceManager.GetString("Start3_OnlyWithBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always read ähnelt.
        /// </summary>
        public static string Start3_ReadAlways {
            get {
                return ResourceManager.GetString("Start3_ReadAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always read and ask before writing ähnelt.
        /// </summary>
        public static string Start3_ReadAlwaysAskWrite {
            get {
                return ResourceManager.GetString("Start3_ReadAlwaysAskWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always read and always create or update contact ähnelt.
        /// </summary>
        public static string Start3_ReadAlwaysWrite {
            get {
                return ResourceManager.GetString("Start3_ReadAlwaysWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read once ähnelt.
        /// </summary>
        public static string Start3_ReadOnce {
            get {
                return ResourceManager.GetString("Start3_ReadOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Which contacts? ähnelt.
        /// </summary>
        public static string Start3_WhichContacts {
            get {
                return ResourceManager.GetString("Start3_WhichContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission not granted, that&apos;s ok too ähnelt.
        /// </summary>
        public static string Permission_Denied {
            get {
                return ResourceManager.GetString("Permission_Denied", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The permission was already denied... ähnelt.
        /// </summary>
        public static string Permission_DeniedInfo {
            get {
                return ResourceManager.GetString("Permission_DeniedInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission granted ähnelt.
        /// </summary>
        public static string Permission_Granted {
            get {
                return ResourceManager.GetString("Permission_Granted", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please grant permission for this phone now ähnelt.
        /// </summary>
        public static string Permission_GrantRequest {
            get {
                return ResourceManager.GetString("Permission_GrantRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission required ähnelt.
        /// </summary>
        public static string Permission_Needed {
            get {
                return ResourceManager.GetString("Permission_Needed", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Settings ähnelt.
        /// </summary>
        public static string Permission_OpenSettings {
            get {
                return ResourceManager.GetString("Permission_OpenSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        public static string Permission_Result {
            get {
                return ResourceManager.GetString("Permission_Result", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start dialog ähnelt.
        /// </summary>
        public static string Permission_StartDialog {
            get {
                return ResourceManager.GetString("Permission_StartDialog", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for permission... ähnelt.
        /// </summary>
        public static string Permission_Waiting {
            get {
                return ResourceManager.GetString("Permission_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This can also be set manually for each entry ähnelt.
        /// </summary>
        public static string Start5_ManualNote {
            get {
                return ResourceManager.GetString("Start5_ManualNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to be reminded on the exact day or also three days before or even 3 times? ähnelt.
        /// </summary>
        public static string Start5_ReminderQuestion {
            get {
                return ResourceManager.GetString("Start5_ReminderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendar Export ähnelt.
        /// </summary>
        public static string Start9_CalendarExport {
            get {
                return ResourceManager.GetString("Start9_CalendarExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device calendar ähnelt.
        /// </summary>
        public static string Start9_DeviceCalendar {
            get {
                return ResourceManager.GetString("Start9_DeviceCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Google Calendar ähnelt.
        /// </summary>
        public static string Start9_GoogleCalendar {
            get {
                return ResourceManager.GetString("Start9_GoogleCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grant access ähnelt.
        /// </summary>
        public static string Start9_GrantAccess {
            get {
                return ResourceManager.GetString("Start9_GrantAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outlook Calendar ähnelt.
        /// </summary>
        public static string Start9_OutlookCalendar {
            get {
                return ResourceManager.GetString("Start9_OutlookCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single per email ähnelt.
        /// </summary>
        public static string Start9_SingleEmail {
            get {
                return ResourceManager.GetString("Start9_SingleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write to calendar ähnelt.
        /// </summary>
        public static string Start9_WriteToCalendar {
            get {
                return ResourceManager.GetString("Start9_WriteToCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account ähnelt.
        /// </summary>
        public static string Tab_Account {
            get {
                return ResourceManager.GetString("Tab_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overview ähnelt.
        /// </summary>
        public static string Tab_Overview {
            get {
                return ResourceManager.GetString("Tab_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        public static string Tab_Privacy {
            get {
                return ResourceManager.GetString("Tab_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminders ähnelt.
        /// </summary>
        public static string Tab_Reminders {
            get {
                return ResourceManager.GetString("Tab_Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Tab_Settings {
            get {
                return ResourceManager.GetString("Tab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show All ähnelt.
        /// </summary>
        public static string Tab_ShowAll {
            get {
                return ResourceManager.GetString("Tab_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        public static string Time_Hours {
            get {
                return ResourceManager.GetString("Time_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minutes ähnelt.
        /// </summary>
        public static string Time_Minutes {
            get {
                return ResourceManager.GetString("Time_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From now on, remember every important birthday with our help. ähnelt.
        /// </summary>
        public static string Welcome_1_Text_1 {
            get {
                return ResourceManager.GetString("Welcome_1_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First, we need to configure some important settings. ähnelt.
        /// </summary>
        public static string Welcome_1_Text_2 {
            get {
                return ResourceManager.GetString("Welcome_1_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Sources ähnelt.
        /// </summary>
        public static string Welcome_DataSources {
            get {
                return ResourceManager.GetString("Welcome_DataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to Birthday Reminder ähnelt.
        /// </summary>
        public static string Welcome_Header {
            get {
                return ResourceManager.GetString("Welcome_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome ähnelt.
        /// </summary>
        public static string Welcome_Header_Title {
            get {
                return ResourceManager.GetString("Welcome_Header_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name order ähnelt.
        /// </summary>
        public static string Settings_NameDirection {
            get {
                return ResourceManager.GetString("Settings_NameDirection", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First name Last name ähnelt.
        /// </summary>
        public static string NameDirection_FirstFirstName {
            get {
                return ResourceManager.GetString("NameDirection_FirstFirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last name, First name ähnelt.
        /// </summary>
        public static string NameDirection_FirstLastName {
            get {
                return ResourceManager.GetString("NameDirection_FirstLastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder Number -{0}- ähnelt.
        /// </summary>
        public static string Settings_ReminderNumber {
            get {
                return ResourceManager.GetString("Settings_ReminderNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free Reminders ähnelt.
        /// </summary>
        public static string Settings_FreeReminders {
            get {
                return ResourceManager.GetString("Settings_FreeReminders", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminders with Subscription ähnelt.
        /// </summary>
        public static string Settings_SubscriptionReminders {
            get {
                return ResourceManager.GetString("Settings_SubscriptionReminders", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free Reminders ähnelt.
        /// </summary>
        public static string Help_FreeReminders_Header {
            get {
                return ResourceManager.GetString("Help_FreeReminders_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge für Help_FreeReminders_Content_1.
        /// </summary>
        public static string Help_FreeReminders_Content_1 {
            get {
                return ResourceManager.GetString("Help_FreeReminders_Content_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge für Help_FreeReminders_Content_2.
        /// </summary>
        public static string Help_FreeReminders_Content_2 {
            get {
                return ResourceManager.GetString("Help_FreeReminders_Content_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report Bug ähnelt.
        /// </summary>
        public static string Support_ReportBug {
            get {
                return ResourceManager.GetString("Support_ReportBug", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suggest Improvement ähnelt.
        /// </summary>
        public static string Support_FeatureRequest {
            get {
                return ResourceManager.GetString("Support_FeatureRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Give Feedback ähnelt.
        /// </summary>
        public static string Support_Feedback {
            get {
                return ResourceManager.GetString("Support_Feedback", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Entry ähnelt.
        /// </summary>
        public static string Page_NewSupport_Title {
            get {
                return ResourceManager.GetString("Page_NewSupport_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support Overview ähnelt.
        /// </summary>
        public static string Page_SupportOverview_Title {
            get {
                return ResourceManager.GetString("Page_SupportOverview_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support Details ähnelt.
        /// </summary>
        public static string Page_SupportDetail_Title {
            get {
                return ResourceManager.GetString("Page_SupportDetail_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string Support_Title {
            get {
                return ResourceManager.GetString("Support_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Support_Text {
            get {
                return ResourceManager.GetString("Support_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bug ähnelt.
        /// </summary>
        public static string Support_Type_Bug {
            get {
                return ResourceManager.GetString("Support_Type_Bug", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feature Request ähnelt.
        /// </summary>
        public static string Support_Type_FeatureRequest {
            get {
                return ResourceManager.GetString("Support_Type_FeatureRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback ähnelt.
        /// </summary>
        public static string Support_Type_Feedback {
            get {
                return ResourceManager.GetString("Support_Type_Feedback", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        public static string Reminder_Status_Free {
            get {
                return ResourceManager.GetString("Reminder_Status_Free", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free (limited) ähnelt.
        /// </summary>
        public static string Reminder_Status_FreeLimited {
            get {
                return ResourceManager.GetString("Reminder_Status_FreeLimited", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently free ähnelt.
        /// </summary>
        public static string Reminder_Status_FreeCurrently {
            get {
                return ResourceManager.GetString("Reminder_Status_FreeCurrently", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requires subscription ähnelt.
        /// </summary>
        public static string Reminder_Status_Subscription {
            get {
                return ResourceManager.GetString("Reminder_Status_Subscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        public static string General_Label_Active {
            get {
                return ResourceManager.GetString("General_Label_Active", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        public static string General_Label_Time {
            get {
                return ResourceManager.GetString("General_Label_Time", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderNotification_Header
        /// </summary>
        public static string Help_ReminderNotification_Header {
            get {
                return ResourceManager.GetString("Help_ReminderNotification_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderNotification_Content_1
        /// </summary>
        public static string Help_ReminderNotification_Content_1 {
            get {
                return ResourceManager.GetString("Help_ReminderNotification_Content_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderNotification_Content_2
        /// </summary>
        public static string Help_ReminderNotification_Content_2 {
            get {
                return ResourceManager.GetString("Help_ReminderNotification_Content_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderAlarm_Header
        /// </summary>
        public static string Help_ReminderAlarm_Header {
            get {
                return ResourceManager.GetString("Help_ReminderAlarm_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderAlarm_Content_1
        /// </summary>
        public static string Help_ReminderAlarm_Content_1 {
            get {
                return ResourceManager.GetString("Help_ReminderAlarm_Content_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderAlarm_Content_2
        /// </summary>
        public static string Help_ReminderAlarm_Content_2 {
            get {
                return ResourceManager.GetString("Help_ReminderAlarm_Content_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderEmail_Header
        /// </summary>
        public static string Help_ReminderEmail_Header {
            get {
                return ResourceManager.GetString("Help_ReminderEmail_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderEmail_Content_1
        /// </summary>
        public static string Help_ReminderEmail_Content_1 {
            get {
                return ResourceManager.GetString("Help_ReminderEmail_Content_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderEmail_Content_2
        /// </summary>
        public static string Help_ReminderEmail_Content_2 {
            get {
                return ResourceManager.GetString("Help_ReminderEmail_Content_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderSignal_Header
        /// </summary>
        public static string Help_ReminderSignal_Header {
            get {
                return ResourceManager.GetString("Help_ReminderSignal_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderSignal_Content_1
        /// </summary>
        public static string Help_ReminderSignal_Content_1 {
            get {
                return ResourceManager.GetString("Help_ReminderSignal_Content_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderSignal_Content_2
        /// </summary>
        public static string Help_ReminderSignal_Content_2 {
            get {
                return ResourceManager.GetString("Help_ReminderSignal_Content_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderSms_Header
        /// </summary>
        public static string Help_ReminderSms_Header {
            get {
                return ResourceManager.GetString("Help_ReminderSms_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderSms_Content_1
        /// </summary>
        public static string Help_ReminderSms_Content_1 {
            get {
                return ResourceManager.GetString("Help_ReminderSms_Content_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderSms_Content_2
        /// </summary>
        public static string Help_ReminderSms_Content_2 {
            get {
                return ResourceManager.GetString("Help_ReminderSms_Content_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderWhatsApp_Header
        /// </summary>
        public static string Help_ReminderWhatsApp_Header {
            get {
                return ResourceManager.GetString("Help_ReminderWhatsApp_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderWhatsApp_Content_1
        /// </summary>
        public static string Help_ReminderWhatsApp_Content_1 {
            get {
                return ResourceManager.GetString("Help_ReminderWhatsApp_Content_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Help_ReminderWhatsApp_Content_2
        /// </summary>
        public static string Help_ReminderWhatsApp_Content_2 {
            get {
                return ResourceManager.GetString("Help_ReminderWhatsApp_Content_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your timezone: {0}. You can change this in settings. ähnelt.
        ///   Help_Timezone_Note
        /// </summary>
        public static string Help_Timezone_Note {
            get {
                return ResourceManager.GetString("Help_Timezone_Note", resourceCulture);
            }
        }

        /// <summary>
        ///   Timezone_UTC
        /// </summary>
        public static string Timezone_UTC {
            get {
                return ResourceManager.GetString("Timezone_UTC", resourceCulture);
            }
        }

        /// <summary>
        ///   Timezone_Unknown
        /// </summary>
        public static string Timezone_Unknown {
            get {
                return ResourceManager.GetString("Timezone_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Browser_OpenExternal
        /// </summary>
        public static string Browser_OpenExternal {
            get {
                return ResourceManager.GetString("Browser_OpenExternal", resourceCulture);
            }
        }

        /// <summary>
        ///   Timezone_MoreInfo
        /// </summary>
        public static string Timezone_MoreInfo {
            get {
                return ResourceManager.GetString("Timezone_MoreInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   PurchaseAbo_Title
        /// </summary>
        public static string PurchaseAbo_Title {
            get {
                return ResourceManager.GetString("PurchaseAbo_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   PurchaseAbo_CardHeader
        /// </summary>
        public static string PurchaseAbo_CardHeader {
            get {
                return ResourceManager.GetString("PurchaseAbo_CardHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   PurchaseAbo_Description
        /// </summary>
        public static string PurchaseAbo_Description {
            get {
                return ResourceManager.GetString("PurchaseAbo_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   PurchaseAbo_Button
        /// </summary>
        public static string PurchaseAbo_Button {
            get {
                return ResourceManager.GetString("PurchaseAbo_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   PurchaseAbo_FeaturesHeader
        /// </summary>
        public static string PurchaseAbo_FeaturesHeader {
            get {
                return ResourceManager.GetString("PurchaseAbo_FeaturesHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   PurchaseAbo_Feature_Sms
        /// </summary>
        public static string PurchaseAbo_Feature_Sms {
            get {
                return ResourceManager.GetString("PurchaseAbo_Feature_Sms", resourceCulture);
            }
        }

        /// <summary>
        ///   PurchaseAbo_Feature_WhatsApp
        /// </summary>
        public static string PurchaseAbo_Feature_WhatsApp {
            get {
                return ResourceManager.GetString("PurchaseAbo_Feature_WhatsApp", resourceCulture);
            }
        }

        /// <summary>
        ///   PurchaseAbo_Feature_Email
        /// </summary>
        public static string PurchaseAbo_Feature_Email {
            get {
                return ResourceManager.GetString("PurchaseAbo_Feature_Email", resourceCulture);
            }
        }

        /// <summary>
        ///   PurchaseAbo_ComingSoon
        /// </summary>
        public static string PurchaseAbo_ComingSoon {
            get {
                return ResourceManager.GetString("PurchaseAbo_ComingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   ContextMenu_Subscribe
        /// </summary>
        public static string ContextMenu_Subscribe {
            get {
                return ResourceManager.GetString("ContextMenu_Subscribe", resourceCulture);
            }
        }
    }
}
