//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MobileLanguages;

public class Resources
{
	private static global::System.Resources.ResourceManager? resourceMan;
	private static global::System.Globalization.CultureInfo? resourceCulture;

	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (resourceMan is null)
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileLanguages.Resources", typeof(Resources).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}

	public static global::System.Globalization.CultureInfo? Culture
	{
		get { return resourceCulture; }
		set { resourceCulture = value; }
	}

	public static string Page_Main_Title => ResourceManager.GetString("Page_Main_Title", resourceCulture) ?? "";
	public static string Page_Main_MissedTitle => ResourceManager.GetString("Page_Main_MissedTitle", resourceCulture) ?? "";
	public static string Page_Main_UpcomingTitle => ResourceManager.GetString("Page_Main_UpcomingTitle", resourceCulture) ?? "";
	public static string Page_Main_NewBirthday => ResourceManager.GetString("Page_Main_NewBirthday", resourceCulture) ?? "";
	public static string Page_AskForContacts_Title => ResourceManager.GetString("Page_AskForContacts_Title", resourceCulture) ?? "";
	public static string Page_AskForContacts_Question => ResourceManager.GetString("Page_AskForContacts_Question", resourceCulture) ?? "";
	public static string Page_AskForContacts_ManualInput => ResourceManager.GetString("Page_AskForContacts_ManualInput", resourceCulture) ?? "";
	public static string Page_AskForContacts_FromContacts => ResourceManager.GetString("Page_AskForContacts_FromContacts", resourceCulture) ?? "";
	public static string Page_NewBirthday_Title => ResourceManager.GetString("Page_NewBirthday_Title", resourceCulture) ?? "";
	public static string Page_AllBirthdays_Title => ResourceManager.GetString("Page_AllBirthdays_Title", resourceCulture) ?? "";
	public static string Page_Settings_Title => ResourceManager.GetString("Page_Settings_Title", resourceCulture) ?? "";
	public static string Page_Privacy_Title => ResourceManager.GetString("Page_Privacy_Title", resourceCulture) ?? "";
	public static string Tab_ShowAll => ResourceManager.GetString("Tab_ShowAll", resourceCulture) ?? "";
	public static string Tab_Settings => ResourceManager.GetString("Tab_Settings", resourceCulture) ?? "";
	public static string Tab_Privacy => ResourceManager.GetString("Tab_Privacy", resourceCulture) ?? "";
	public static string General_Button_Save => ResourceManager.GetString("General_Button_Save", resourceCulture) ?? "";
	public static string General_Button_Cancel => ResourceManager.GetString("General_Button_Cancel", resourceCulture) ?? "";
	public static string General_Button_Delete => ResourceManager.GetString("General_Button_Delete", resourceCulture) ?? "";
	public static string General_Button_New => ResourceManager.GetString("General_Button_New", resourceCulture) ?? "";
	public static string General_Label_Name => ResourceManager.GetString("General_Label_Name", resourceCulture) ?? "";
	public static string General_Label_Birthday => ResourceManager.GetString("General_Label_Birthday", resourceCulture) ?? "";
	public static string General_Button_Next => ResourceManager.GetString("General_Button_Next", resourceCulture) ?? "";
	public static string General_Button_Back => ResourceManager.GetString("General_Button_Back", resourceCulture) ?? "";
	public static string General_Button_Finish => ResourceManager.GetString("General_Button_Finish", resourceCulture) ?? "";
	public static string General_Button_OK => ResourceManager.GetString("General_Button_OK", resourceCulture) ?? "";
	public static string Page_Welcome_Title => ResourceManager.GetString("Page_Welcome_Title", resourceCulture) ?? "";
	public static string Welcome_Header => ResourceManager.GetString("Welcome_Header", resourceCulture) ?? "";
	public static string Welcome_DataSources => ResourceManager.GetString("Welcome_DataSources", resourceCulture) ?? "";
	public static string Settings_Language => ResourceManager.GetString("Settings_Language", resourceCulture) ?? "";
	public static string Settings_ReminderTime => ResourceManager.GetString("Settings_ReminderTime", resourceCulture) ?? "";
	public static string Time_Hours => ResourceManager.GetString("Time_Hours", resourceCulture) ?? "";
	public static string Time_Minutes => ResourceManager.GetString("Time_Minutes", resourceCulture) ?? "";
	public static string Settings_Contacts => ResourceManager.GetString("Settings_Contacts", resourceCulture) ?? "";
	public static string Settings_ReadContactsBirthday => ResourceManager.GetString("Settings_ReadContactsBirthday", resourceCulture) ?? "";
	public static string Settings_ReadContactsBirthday_Desc => ResourceManager.GetString("Settings_ReadContactsBirthday_Desc", resourceCulture) ?? "";
	public static string Settings_ReadContactsAll => ResourceManager.GetString("Settings_ReadContactsAll", resourceCulture) ?? "";
	public static string Settings_ReadContactsAll_Desc => ResourceManager.GetString("Settings_ReadContactsAll_Desc", resourceCulture) ?? "";
	public static string Settings_WriteContacts => ResourceManager.GetString("Settings_WriteContacts", resourceCulture) ?? "";
	public static string Settings_WriteContacts_Desc => ResourceManager.GetString("Settings_WriteContacts_Desc", resourceCulture) ?? "";
	public static string Settings_Calendars => ResourceManager.GetString("Settings_Calendars", resourceCulture) ?? "";
	public static string Settings_ReadCalendars => ResourceManager.GetString("Settings_ReadCalendars", resourceCulture) ?? "";
	public static string Settings_ReadCalendars_Desc => ResourceManager.GetString("Settings_ReadCalendars_Desc", resourceCulture) ?? "";
	public static string Settings_WriteCalendars => ResourceManager.GetString("Settings_WriteCalendars", resourceCulture) ?? "";
	public static string Settings_WriteCalendars_Desc => ResourceManager.GetString("Settings_WriteCalendars_Desc", resourceCulture) ?? "";
	public static string Settings_SelectCalendars => ResourceManager.GetString("Settings_SelectCalendars", resourceCulture) ?? "";
	public static string Permission_Required => ResourceManager.GetString("Permission_Required", resourceCulture) ?? "";
	public static string Permission_ContactsRead_Denied => ResourceManager.GetString("Permission_ContactsRead_Denied", resourceCulture) ?? "";
	public static string Permission_ContactsWrite_Denied => ResourceManager.GetString("Permission_ContactsWrite_Denied", resourceCulture) ?? "";
	public static string Permission_CalendarRead_Denied => ResourceManager.GetString("Permission_CalendarRead_Denied", resourceCulture) ?? "";
	public static string Permission_CalendarWrite_Denied => ResourceManager.GetString("Permission_CalendarWrite_Denied", resourceCulture) ?? "";
	public static string Calendar_Default => ResourceManager.GetString("Calendar_Default", resourceCulture) ?? "";
	public static string Calendar_Personal => ResourceManager.GetString("Calendar_Personal", resourceCulture) ?? "";
	public static string Calendar_Work => ResourceManager.GetString("Calendar_Work", resourceCulture) ?? "";
	public static string Calendar_Family => ResourceManager.GetString("Calendar_Family", resourceCulture) ?? "";
	public static string Settings_Saved_Title => ResourceManager.GetString("Settings_Saved_Title", resourceCulture) ?? "";
	public static string Settings_Saved_Message => ResourceManager.GetString("Settings_Saved_Message", resourceCulture) ?? "";
	public static string Welcome_Header_Title => ResourceManager.GetString("Welcome_Header_Title", resourceCulture) ?? "";
	public static string Welcome_1_Text_1 => ResourceManager.GetString("Welcome_1_Text_1", resourceCulture) ?? "";
	public static string Welcome_1_Text_2 => ResourceManager.GetString("Welcome_1_Text_2", resourceCulture) ?? "";
	public static string Settings_Theme => ResourceManager.GetString("Settings_Theme", resourceCulture) ?? "";
	public static string Settings_Theme_Light => ResourceManager.GetString("Settings_Theme_Light", resourceCulture) ?? "";
	public static string Settings_Theme_Dark => ResourceManager.GetString("Settings_Theme_Dark", resourceCulture) ?? "";
	public static string Settings_Theme_System => ResourceManager.GetString("Settings_Theme_System", resourceCulture) ?? "";
	public static string Date_Day => ResourceManager.GetString("Date_Day", resourceCulture) ?? "";
	public static string Date_Month => ResourceManager.GetString("Date_Month", resourceCulture) ?? "";
	public static string Date_Year => ResourceManager.GetString("Date_Year", resourceCulture) ?? "";
	public static string Month_January => ResourceManager.GetString("Month_January", resourceCulture) ?? "";
	public static string Month_February => ResourceManager.GetString("Month_February", resourceCulture) ?? "";
	public static string Month_March => ResourceManager.GetString("Month_March", resourceCulture) ?? "";
	public static string Month_April => ResourceManager.GetString("Month_April", resourceCulture) ?? "";
	public static string Month_May => ResourceManager.GetString("Month_May", resourceCulture) ?? "";
	public static string Month_June => ResourceManager.GetString("Month_June", resourceCulture) ?? "";
	public static string Month_July => ResourceManager.GetString("Month_July", resourceCulture) ?? "";
	public static string Month_August => ResourceManager.GetString("Month_August", resourceCulture) ?? "";
	public static string Month_September => ResourceManager.GetString("Month_September", resourceCulture) ?? "";
	public static string Month_October => ResourceManager.GetString("Month_October", resourceCulture) ?? "";
	public static string Month_November => ResourceManager.GetString("Month_November", resourceCulture) ?? "";
	public static string Month_December => ResourceManager.GetString("Month_December", resourceCulture) ?? "";
}
